//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResrMvcApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientMasterContract", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class ClientMasterContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Client_NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientID {
            get {
                return this.ClientIDField;
            }
            set {
                if ((this.ClientIDField.Equals(value) != true)) {
                    this.ClientIDField = value;
                    this.RaisePropertyChanged("ClientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Client_Name {
            get {
                return this.Client_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Client_NameField, value) != true)) {
                    this.Client_NameField = value;
                    this.RaisePropertyChanged("Client_Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BrandMasterContract", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class BrandMasterContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BrandIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Brand_NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BrandID {
            get {
                return this.BrandIDField;
            }
            set {
                if ((this.BrandIDField.Equals(value) != true)) {
                    this.BrandIDField = value;
                    this.RaisePropertyChanged("BrandID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brand_Name {
            get {
                return this.Brand_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Brand_NameField, value) != true)) {
                    this.Brand_NameField = value;
                    this.RaisePropertyChanged("Brand_Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstimateDataContract", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class EstimateDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgencyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BrandIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CampaignNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EstimateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstimateNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PeriodFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PeriodToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float aacperField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime podateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ponoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float sacperField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgencyName {
            get {
                return this.AgencyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AgencyNameField, value) != true)) {
                    this.AgencyNameField = value;
                    this.RaisePropertyChanged("AgencyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BrandID {
            get {
                return this.BrandIDField;
            }
            set {
                if ((this.BrandIDField.Equals(value) != true)) {
                    this.BrandIDField = value;
                    this.RaisePropertyChanged("BrandID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CampaignName {
            get {
                return this.CampaignNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CampaignNameField, value) != true)) {
                    this.CampaignNameField = value;
                    this.RaisePropertyChanged("CampaignName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientID {
            get {
                return this.ClientIDField;
            }
            set {
                if ((this.ClientIDField.Equals(value) != true)) {
                    this.ClientIDField = value;
                    this.RaisePropertyChanged("ClientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EstimateDate {
            get {
                return this.EstimateDateField;
            }
            set {
                if ((this.EstimateDateField.Equals(value) != true)) {
                    this.EstimateDateField = value;
                    this.RaisePropertyChanged("EstimateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstimateNo {
            get {
                return this.EstimateNoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstimateNoField, value) != true)) {
                    this.EstimateNoField = value;
                    this.RaisePropertyChanged("EstimateNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PeriodFrom {
            get {
                return this.PeriodFromField;
            }
            set {
                if ((this.PeriodFromField.Equals(value) != true)) {
                    this.PeriodFromField = value;
                    this.RaisePropertyChanged("PeriodFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PeriodTo {
            get {
                return this.PeriodToField;
            }
            set {
                if ((this.PeriodToField.Equals(value) != true)) {
                    this.PeriodToField = value;
                    this.RaisePropertyChanged("PeriodTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float aacper {
            get {
                return this.aacperField;
            }
            set {
                if ((this.aacperField.Equals(value) != true)) {
                    this.aacperField = value;
                    this.RaisePropertyChanged("aacper");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime podate {
            get {
                return this.podateField;
            }
            set {
                if ((this.podateField.Equals(value) != true)) {
                    this.podateField = value;
                    this.RaisePropertyChanged("podate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pono {
            get {
                return this.ponoField;
            }
            set {
                if ((object.ReferenceEquals(this.ponoField, value) != true)) {
                    this.ponoField = value;
                    this.RaisePropertyChanged("pono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float sacper {
            get {
                return this.sacperField;
            }
            set {
                if ((this.sacperField.Equals(value) != true)) {
                    this.sacperField = value;
                    this.RaisePropertyChanged("sacper");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IEstimateService1")]
    public interface IEstimateService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstimateService1/GetClientMaster", ReplyAction="http://tempuri.org/IEstimateService1/GetClientMasterResponse")]
        ResrMvcApp.ServiceReference1.ClientMasterContract[] GetClientMaster();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstimateService1/GetClientMaster", ReplyAction="http://tempuri.org/IEstimateService1/GetClientMasterResponse")]
        System.Threading.Tasks.Task<ResrMvcApp.ServiceReference1.ClientMasterContract[]> GetClientMasterAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstimateService1/GetBrandMaster", ReplyAction="http://tempuri.org/IEstimateService1/GetBrandMasterResponse")]
        ResrMvcApp.ServiceReference1.BrandMasterContract[] GetBrandMaster();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstimateService1/GetBrandMaster", ReplyAction="http://tempuri.org/IEstimateService1/GetBrandMasterResponse")]
        System.Threading.Tasks.Task<ResrMvcApp.ServiceReference1.BrandMasterContract[]> GetBrandMasterAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstimateService1/GetAllEstimate", ReplyAction="http://tempuri.org/IEstimateService1/GetAllEstimateResponse")]
        ResrMvcApp.ServiceReference1.EstimateDataContract[] GetAllEstimate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstimateService1/GetAllEstimate", ReplyAction="http://tempuri.org/IEstimateService1/GetAllEstimateResponse")]
        System.Threading.Tasks.Task<ResrMvcApp.ServiceReference1.EstimateDataContract[]> GetAllEstimateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstimateService1/AddNewEstimate", ReplyAction="http://tempuri.org/IEstimateService1/AddNewEstimateResponse")]
        bool AddNewEstimate(ResrMvcApp.ServiceReference1.EstimateDataContract estimate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstimateService1/AddNewEstimate", ReplyAction="http://tempuri.org/IEstimateService1/AddNewEstimateResponse")]
        System.Threading.Tasks.Task<bool> AddNewEstimateAsync(ResrMvcApp.ServiceReference1.EstimateDataContract estimate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEstimateService1Channel : ResrMvcApp.ServiceReference1.IEstimateService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EstimateService1Client : System.ServiceModel.ClientBase<ResrMvcApp.ServiceReference1.IEstimateService1>, ResrMvcApp.ServiceReference1.IEstimateService1 {
        
        public EstimateService1Client() {
        }
        
        public EstimateService1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EstimateService1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstimateService1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstimateService1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ResrMvcApp.ServiceReference1.ClientMasterContract[] GetClientMaster() {
            return base.Channel.GetClientMaster();
        }
        
        public System.Threading.Tasks.Task<ResrMvcApp.ServiceReference1.ClientMasterContract[]> GetClientMasterAsync() {
            return base.Channel.GetClientMasterAsync();
        }
        
        public ResrMvcApp.ServiceReference1.BrandMasterContract[] GetBrandMaster() {
            return base.Channel.GetBrandMaster();
        }
        
        public System.Threading.Tasks.Task<ResrMvcApp.ServiceReference1.BrandMasterContract[]> GetBrandMasterAsync() {
            return base.Channel.GetBrandMasterAsync();
        }
        
        public ResrMvcApp.ServiceReference1.EstimateDataContract[] GetAllEstimate() {
            return base.Channel.GetAllEstimate();
        }
        
        public System.Threading.Tasks.Task<ResrMvcApp.ServiceReference1.EstimateDataContract[]> GetAllEstimateAsync() {
            return base.Channel.GetAllEstimateAsync();
        }
        
        public bool AddNewEstimate(ResrMvcApp.ServiceReference1.EstimateDataContract estimate) {
            return base.Channel.AddNewEstimate(estimate);
        }
        
        public System.Threading.Tasks.Task<bool> AddNewEstimateAsync(ResrMvcApp.ServiceReference1.EstimateDataContract estimate) {
            return base.Channel.AddNewEstimateAsync(estimate);
        }
    }
}
